name: "Pull Request Docs Check"
on: [push]
permissions:
  contents: write

jobs:
  # anything in the job "docs" is executed on the same runner
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/