name: "Push Docs Build"
on: [push]
permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          wget https://bootstrap.pypa.io/get-pip.py
          python get-pip.py
          cd $GITHUB_WORKSPACE/docs
          python -m pip install -r requirements.txt
      - name: Make HTML
        run: |
          cd $GITHUB_WORKSPACE/docs
          TZ=UTC make html
      - name: Publish Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ env.GITHUB_ACTIONS == true && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/