name: "Pull Request Docs Check"
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          face_orphan: true